name: Deploy Action
description: Composite action to deploy the application to the specified environment

inputs:
  environment:
    description: 'Environment to deploy the application to'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Delivery Pipeline
      uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop Existing Service
      run: |
        $processExists = pm2 jlist | ConvertFrom-Json | Where-Object { $_.name -eq "books-DEV" }
        if ($processExists) {
          pm2 delete "books-DEV"
        }
        $true
      shell: powershell

    - name: Start Service
      working-directory: python-greetings
      run: |
        run : pm2 start -n "books-${{ inputs.environment }}" index.js -- ${{ inputs.port }}
        Write-Host "Started books-${{ inputs.environment }} service."
      shell: powershell
