name: Sample Book App

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Checkout Delivery Pipeline
      -  uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install Dependencies
        working-directory: python-greetings
        run: |
          echo "Installing all required dependencies..."
          pip3 install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - name: Composite Action Deploy Dev
      - uses: ./.github/actions/deploy-action
        with:
          environment:  'DEV'
