name: Sample Book App

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Print greeting
        run: echo Hello, world!
  hello:
    runs-on: npm
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Check node version
        run: node --version

# jobs:
#   install-pip-deps:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout Delivery Pipeline
#       - uses: actions/checkout@v3.5.2

#       - name: Install Dependencies
#         run: |
#           echo "Installing all required dependencies..."
#           cd python-greetings
#           pip3 install -r requirements.txt

#   deploy-to-dev:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout Delivery Pipeline
#       - uses: actions/checkout@v3.5.2

#       - name: Composite Action: Deploy Dev
#       - uses: ./.github/actions/deploy-action
#         with:
#           environment:  'DEV'


#   test-on-dev:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout Test Delivery Pipeline
#       - uses: actions/checkout@v3.5.2

#       - name: Composite Action: Test Dev
#       - uses: ./.github/actions/test-action
#         with:
#           environment: 'DEV'
